# pnpm workspace definitions
packages:
  # apps has all the webapps that could be run locally or deployed
  - 'apps/*'
  # shared ui components, icons, and configuration files for apps
  - 'packages/*'
